version: '2'

services:

  web:
    restart: always
    build: .
    ports:
      - "8080:80"
#    volumes:
#      - ./angular:/usr/src/app
#      - ./nginx:/etc/nginx
#      #- node_modules:/usr/src/app/node_modules
#
##volumes:
##node_modules: {}